add examples of while loops
mhorod/tcs-lang-compiler pull request #11
Opened 2024-10-10 16:33 UTC by km1chno

Resolves #10 

TODO:
- file extensions

2024-10-12 08:58 UTC, mhorod reviewed
> file extensions

We can use `.ccp`

2024-10-12 08:58 UTC, mhorod commented on examples/incorrect/while.ag
Please split these examples across separate files

2024-10-12 14:13 UTC, mhorod requested changes
.

2024-10-14 13:59 UTC, km1chno commented on examples/incorrect/while.ag
done

2024-10-14 14:11 UTC, mhorod approved these changes

2024-10-14 15:04 UTC, merged