add examples of if statements
mhorod/tcs-lang-compiler pull request #9
Opened 2024-10-10 16:16 UTC by km1chno

Resolves #6

2024-10-12 08:47 UTC, mhorod requested changes
> file extension

We can use `.ccp` now

2024-10-12 08:47 UTC, mhorod commented on examples/incorrect/conditional.ag
Please split these examples into separate files with single error each.

2024-10-14 14:03 UTC, km1chno commented on examples/incorrect/conditional.ag
done

2024-10-14 14:11 UTC, mhorod approved these changes

2024-10-14 15:03 UTC, merged